### ISSUE TITLE
申鹤mod的手部服装贴图未完全处理

### ISSUE THREAD

**Issue by myGnauh** [zeroruka/GI-Assets#122]
还保留有黑色的细线，影响美观，希望大佬有时间能修复一下

**Comment by myGnauh** [comment]
![手部](https://user-images.githubusercontent.com/75158806/182078108-ae6f1111-f42f-46e2-ab93-b01c3b11b68f.png)

**Comment by G1025** [comment]
> 你好！我也注意到手部的细线了。我个人认为，这个问题比较容易解决。只要在 Blender 中修改 ShenheBodyDiffuse.dds，把黑线相关的部分，涂成相邻的肤色就可以了。

> 我在作者大大的指导下做出了一点尝试：

![Snipaste：原神：2022-08-10：01-14-03](https://user-images.githubusercontent.com/37666214/183716684-ae54a95e-2f89-4936-acbb-4fc5ef8892b6.png)

> 可以注意到，中指是缺少指甲盖的。目前我正在学习 Blender，努力解决这个问题。**我们认为你可以试着自己来搞定！**

> 最后感谢作者大大在此过程中的答疑解惑！

**Comment by UID-503058116** [comment]
您好！我刚刚尝试修复了ShenheMod手部贴图未完全处理的问题。很抱歉时隔多日才回复您！
这次同时修复解决了中指缺少指甲盖的问题。如果您有新的想法欢迎发布新的issue。感谢您的等待！

![preview_bugfixes](https://user-images.githubusercontent.com/37666214/185359238-3083425c-0c4b-476e-856a-f81d0f0e8e8c.png)

**Comment by zeroruka** [comment]
@UID-503058116 麻烦你重新再开一个pr，谢谢

**Comment by UID-503058116** [comment]
您好！如果当前的Mod仍未满足您的要求，请直接指出它的不足吧。如果您认为issue已解决，及时的close会更好。
