### ISSUE TITLE
[GENERAL]萌新提问：有没有用Photoshop改DDS贴图的教程

### ISSUE THREAD

**Issue by Ksir9er** [zeroruka/GI-Assets#127]
萌新提问：有没有用PS改DDS贴图的教程 Github的文字教程有点捉摸不透 Lightmap看不懂 改完Diffuse贴图导进去 身体肤色和头的肤色不同

**Comment by Ksir9er** [comment]
[Modify Channels] 下载不了 可以上传到工具里面吗？

**Comment by zeroruka** [comment]
[ModifyChannels.zip](https://github.com/zeroruka/GI_Assets/files/9242508/ModifyChannels.zip)

**Comment by Ksir9er** [comment]
多谢大佬 还有个问题 法典里的全文件压缩包是下载不了么 我下载显示404 然后3DM 我现在有些东西也是404 我该怎么解决

**Comment by Ksir9er** [comment]
下载问题已经看到以往回答 正在使用链接下载 看能不能解决。。
