### ISSUE TITLE
[REQUEST] フィッシュモッドが欲しいです R18

### ISSUE THREAD

**Issue by Cesarrrcruz** [zeroruka/GI-Assets#128]
Quisiera solicitar el mod de fischl nsfw

**Comment by Cesarrrcruz** [comment]
Quisiera el mod de fischl

**Comment by UID-503058116** [comment]
Please make the request in English, that’ll make this page reader-friendly. Thank you! Anyway please describe the style you’d like. Add some screenshots would be helpful. Thanks a lot!
