### ISSUE TITLE
[BUG] Warning Mod Bug

### ISSUE THREAD

**Issue by thienha1** [zeroruka/GI-Assets#130]
![Untitled](https://user-images.githubusercontent.com/18132856/182606278-58e0a34e-65cf-48df-bb71-934641dfc2d9.png)

**Comment by shenmo7192** [comment]
Why only developers will fall from the cliff with a warning sign ?
Because they don't care about WARNINGs but only ERRORs

Just ignore it XD

**Comment by UID-503058116** [comment]
The WARNING is not always a big deal, and by the way I think the issue you shot, in actually, is not a bug.
Is the mod working properly? If it’s yes, just ignore the WARNING, try to forget it. That should be enough. Thank you!

**Comment by UID-503058116** [comment]
And also, more details on this issue are necessary.

**Comment by UID-503058116** [comment]
It looks like you're using 3DMigoto, isn't it? I think the mod you loaded might not be suitable for 3DMigoto. It was designed as a SpecialK mod. Please consider replacing it, thank you.
