### ISSUE TITLE
大佬怎么好久不做SK的新贴图了，是不是以后只更新3dm的mod了[REQUEST]

### ISSUE THREAD

**Issue by luoriH** [zeroruka/GI-Assets#136]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by fengyan11** [comment]
个人愚见，sk只有贴图实在没什么好看的，还是3dm的mod比较好看。

**Comment by zeroruka** [comment]
对，以后不会再更新SK贴图了

**Comment by xinhailp** [comment]
感觉sk还可以啊，其实好多人也喜欢sk的，保留原有服装更有感觉

**Comment by fengyan11** [comment]
> 感觉sk还可以啊，其实好多人也喜欢sk的，保留原有服装更有感觉

你不知道的是3dm也能保留原有服装，而且可以做的更涩，毕竟有乳头下面的缝也有不是贴图

**Comment by xinhailp** [comment]
但是好多bug，看着建模不舒服，个人感觉啊，个人

**Comment by luoriH** [comment]
哎嘿，主要是sk我在官服玩一直没封号，3dm改建模绝对刚上线就无了

**Comment by fengyan11** [comment]
> 但是好多bug，看着建模不舒服，个人感觉啊，个人

bug的话确实，可以修啊

**Comment by xinhailp** [comment]
就是sk绫华没有区别，只去掉了内k，其他做的真的很棒（个人感觉），瑟一点就好了没有必要盯着奶t一直看，官服玩也舒服

**Comment by zeroruka** [comment]
我到时候会把所有已有的SK贴图转成3DMigoto的

**Comment by Gen-LLL** [comment]
3dm也不会封的。。。这两者从原理上来说区别并不大

**Comment by fengyan11** [comment]
> 3dm也不会封的。。。这两者从原理上来说区别并不大

别说出来啊，自己偷偷用就好，小心sb跳脸直接被ban掉
