### ISSUE TITLE
[REQUEST]请求大佬把刻晴的胸做的小点

### ISSUE THREAD

**Issue by ilovediluc** [zeroruka/GI-Assets#137]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.
一个事实的胸大小，按着原模型

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by UID-503058116** [comment]
我认为兄弟们不会同意的
是吧

**Comment by UID-503058116** [comment]
您可以考虑下自产自销 谢谢！

**Comment by whfie** [comment]
> 我认为兄弟们不会同意的 是吧

不！兄弟们都同意！ヾ(ﾟ∀ﾟゞ)

**Comment by luoriH** [comment]
只要在合理范围内，请无限大！

**Comment by ilovediluc** [comment]
你们好奇怪啊 想做个妖怪吗？

**Comment by luoluojialuo** [comment]
现在这个比起原模型 也只是下乳侧乳大了两指。比起礼服更只能算是拆东墙补西墙。算不得不事实吧。毕竟谁能定义刻晴有多大呢。

**Comment by shenmo7192** [comment]
> 我认为兄弟们不会同意的 是吧

不是所有人都是巨乳控的 XD
