### ISSUE TITLE
[BUG] failed to load...

### ISSUE THREAD

**Issue by jzp312** [zeroruka/GI-Assets#138]
![ganyu](https://user-images.githubusercontent.com/110847914/183500620-c33f22e0-a377-4ed2-9601-117cb4503d81.JPG)
为什么会这样

**Comment by luoriH** [comment]
你这是官服吧

**Comment by 17333832883** [comment]
文件丢失了重新下

**Comment by jzp312** [comment]
> 文件丢失了重新下

![ganyu1wenjian](https://user-images.githubusercontent.com/110847914/183568766-d9e3cabd-c540-4e6f-b601-9e7f62f6965c.JPG)
文件应该都在啊

**Comment by UID-503058116** [comment]
请提供更多信息。。。。

**Comment by jzp312** [comment]
之前是win7，现在升到win10已经没问题了
