### ISSUE TITLE
大佬，能不能把砂糖的眼镜或者头饰去掉[REQUEST]

### ISSUE THREAD

**Issue by luoriH** [zeroruka/GI-Assets#142]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by luoriH** [comment]
这样能行嘛，感觉砂糖颜值被眼镜封印了

**Comment by luoluojialuo** [comment]
可以的 但我还在想 是否能对砂糖另外做点什么，

**Comment by hidamarink** [comment]
要是里面那件能去干净就好了
![image](https://user-images.githubusercontent.com/16144634/183959138-bd4fde52-00b6-40a4-a258-a03ede480134.png)


> 可以的 但我还在想 是否能对砂糖另外做点什么，

**Comment by luoluojialuo** [comment]
> > 可以的 但我还在想 是否能对砂糖另外做点什么，
> 
> 借个楼，在阴影处凝光这脸也太黑了，有办法解决吗大佬 ![PEB%IH9Y28}}X898}UB}4 O](https://user-images.githubusercontent.com/107903693/183928405-1411d268-b2fc-45a4-b680-f6ca3abf3930.png)

应该是你画面设置的问题，即使我把bloom打开 亮度调最暗，也依然不会有你这么明显。脸有色差是正常的，几乎所有角色脸都比身黑，要不你自己在贴图重新涂一下身体颜色。
![20220811121643](https://user-images.githubusercontent.com/107736073/184064333-c7466b8a-bd64-4a4f-8a14-34d7b7c970dd.png)

**Comment by hidamarink** [comment]
> 可以的 但我还在想 是否能对砂糖另外做点什么，

大佬，那个砂糖的Mod能传个没去掉眼镜的版本吗，没有眼镜砂糖总觉得少了什么。

**Comment by luoluojialuo** [comment]
> > 可以的 但我还在想 是否能对砂糖另外做点什么，
> 
> 大佬，那个砂糖的Mod能传个没去掉眼镜的版本吗，没有眼镜砂糖总觉得少了什么。

有blender的软件嘛？我在自己的库的私人分支里传了工程文件，你只需要合并一下图层导出就可以了。其他都不需要动。之前之后的mod如果有差分版本我都会放工程文件。学会合并与导出可以省很多事。
只需要看[这一页](https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md)教程就可以。

**Comment by hidamarink** [comment]
> > > 可以的 但我还在想 是否能对砂糖另外做点什么，
> > 
> > 
> > 大佬，那个砂糖的Mod能传个没去掉眼镜的版本吗，没有眼镜砂糖总觉得少了什么。
> 
> 有blender的软件嘛？我在自己的库的私人分支里传了工程文件，你只需要合并一下图层导出就可以了。其他都不需要动。之前之后的mod如果有差分版本我都会放工程文件。学会合并与导出可以省很多事。 只需要看[这一页](https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md)教程就可以。
好的好的，我去试试，谢谢大佬
