### ISSUE TITLE
[REQUEST]能否为刻晴添加一个带黑丝的版本，万分感谢！

### ISSUE THREAD

**Issue by Amuase** [zeroruka/GI-Assets#143]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by UID-503058116** [comment]
带黑丝但是没衣服吗?请 清楚地描述您的需求。。。。

**Comment by Amuase** [comment]
![-7ea91fa788bf5dca](https://user-images.githubusercontent.com/110990312/184350301-ab191b2d-0707-4fec-96ba-3281c43b55df.png)
对，就是在原来的版本上能不能只加回原来的黑丝

**Comment by UID-503058116** [comment]
另外提到一点，关于角色的lightmap，这个我认为您使用油漆桶，可以将其全部涂成绿色。颜色越偏向Red则发光强度越低（存疑，我记得好像是这样，反正是lightmap的RB强度比值会改变发光贴图的光照强度），但基本应该是这样子的。

**Comment by UID-503058116** [comment]
我向您推荐这个修改lightmap的方法是因为它非常好操作，而且对角色本身的映像应该微乎其微，至少在我数次实践的观察下应该是这样的。欢迎大佬指正！

**Comment by UID-503058116** [comment]
同时再次补充一点，原神的黑丝似乎不具有非常显著的透明效果，您应该可以直接忽略透明问题，这样就不必在一张diffuse上麻烦的处理2种透明强度了。应该是这样的？

**Comment by Amuase** [comment]
😭😭真的非常感谢您！

**Comment by UID-503058116** [comment]
不客气！祝您顺利。您要求的版本我正在尝试制作...麻烦您等候了！

**Comment by UID-503058116** [comment]
> 您好！刚才我稍微花了一些时间来尝试制作您要求的模型。当然现在它还很粗糙，我正在改进。请问下图就是您需要的样式吗？

![Snipaste：原神：2022-08-15：06-20-09](https://user-images.githubusercontent.com/37666214/184556984-689f8626-f1d2-4913-88e2-7af55085d56f.png)
![Snipaste：原神：2022-08-15：06-20-23](https://user-images.githubusercontent.com/37666214/184556985-ecf7347e-5a6a-4289-9e8e-8a9fba15e57e.png)

> 谢谢！我知道它现在还具有很明显的不足。我正在改进它。很抱歉事隔数日才开始回应您的要求！请原谅。

**Comment by UID-503058116** [comment]
制作完毕后我会将项目文件与 mod一起上传到我的仓库中 到时候要麻烦您亲自来下载了。
首先感谢您的建议！无论是之前还是稍后。

**Comment by Amuase** [comment]
我之前的想象可能类似如下这种样子，当然您的版本也非常优秀，感谢您的辛苦付出，期待大佬您的成品
![Screenshot_20220815_071311_com huawei himovie_edit_91676213098510](https://user-images.githubusercontent.com/110990312/184558605-96009d85-fed8-41d7-b3d3-18d6ecadd5d0.jpg)
![Screenshot_20220815_071057_com huawei himovie_edit_91657801778721](https://user-images.githubusercontent.com/110990312/184558609-b6f4052b-7922-4359-ab3a-ca5f41e5ef55.jpg)

**Comment by UID-503058116** [comment]
也就是把小腹也封上黑丝 只留下缝嘛
好的！感谢您的建议！

**Comment by UID-503058116** [comment]
您提供的照片的确很有参考意义。谢谢！

**Comment by 1008611wu** [comment]
> 制作完毕后我会将项目文件与 mod一起上传到我的仓库中 到时候要麻烦您亲自来下载了。 首先感谢您的建议！无论是之前还是稍后。

您好，请问在哪里下载您的作品
