### ISSUE TITLE
[BUG]3DMigoto Loader无法识别YuanShen.exe文件

### ISSUE THREAD

**Issue by chuichui6** [zeroruka/GI-Assets#144]
![0L2GIC16H0M9NWNFCJ LJ5W](https://user-images.githubusercontent.com/110777968/184089988-e8a26ae1-829b-4ecc-a009-f6782b2b9c0a.png)
![QQ图片20220811155938](https://user-images.githubusercontent.com/110777968/184089997-5f1d96f2-bd60-4e3b-ba57-388d9f105f66.png)
![}X~_IP2P4`R8%4@JJABXZ~R](https://user-images.githubusercontent.com/110777968/184090002-416394ad-2023-4398-ac69-d3b3f0256950.png)

**Comment by Hakureitaiga** [comment]
你的路径添加错了，应该是\而不是/。这是正确的路径示意G:\Genshin Impact\Genshin Impact Game\yuanshen.exe
你可以右击yuanshen.exe选择复制路径

**Comment by luoluojialuo** [comment]
...

**Comment by chuichui6** [comment]
> 

![Uploading image.png…]()

**Comment by chuichui6** [comment]
![Uploading image.png…]()
还是不可以

**Comment by chuichui6** [comment]
> 你的路径添加错了，应该是\而不是/。这是正确的路径示意G：\Genshin Impact\Genshin Impact Game\yuanshen.exe 你可以右击源申.exe选择复制路径

好多好的谢谢

**Comment by UID-503058116** [comment]
你好 已解决的issue别忘了close

**Comment by UID-503058116** [comment]
同时请恁也不要大惊小怪 认定啥都是bug
bug可是没那么好找的哥
