### ISSUE TITLE
[REQUEST] 希望可以分享一下甘雨ver1的blend

### ISSUE THREAD

**Issue by luoluojialuo** [zeroruka/GI-Assets#146]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

虽然芭芭拉blend的效果差不多 ，但是芭芭拉没有胸口物理效果，自己涂权重还是有点为难了。若是能提供甘雨blend文件就好了。

**Comment by zeroruka** [comment]
已添加到库里了
