### ISSUE TITLE
[REQUEST]RaidenShogun 3dm Mod plz 

### ISSUE THREAD

**Issue by whiost** [zeroruka/GI-Assets#150]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**

RaidenShogun 3dm like Shenhe or Yea

**Additional context**

![preview](https://user-images.githubusercontent.com/83504710/185016734-68db715a-4747-4efe-821a-693ba1439df4.png)

**Comment by Krentelion** [comment]
Raiden already has an existing 3DMigoto mod [here](https://github.com/zeroruka/GIAssets/tree/main/Mods/3Dmigoto/Mods%20(nsfw)/Raiden), however you haven't specified a different type of mod for her so I cannot assist you further.

**Comment by UID-503058116** [comment]
As @Krentelion mentioned, there is already a 3DMigoto mod for her. If you want a new skin for Raiden Shogun, please describe the style you’d like, and add some screenshots about it. That’ll be most helpful. Thank you!

**Comment by whiost** [comment]
Sorry,I mean, The existing 3dm is just a SK. It can be better like Shenhe or Yea

**Comment by UID-503058116** [comment]
OK, I got it. Thanks a lot! I will try.
![Snipaste：Snipper - Snipaste：2022-08-17：13-04-51](https://user-images.githubusercontent.com/37666214/185038935-5c463fa6-b6b6-46df-a2a2-89a2d1491072.png)

**Comment by whiost** [comment]
I see ,Thank you so much

**Comment by UID-503058116** [comment]
> It's my pleasure. :)
![QQ图片20220817132155](https://user-images.githubusercontent.com/37666214/185041132-534d0a53-380d-41a2-b04d-55a5de9e694b.jpg)

**Comment by shenmo7192** [comment]
> > Anytime my friend. :)
> 
> ![QQ图片20220817132155](https://user-images.githubusercontent.com/37666214/185041132-534d0a53-380d-41a2-b04d-55a5de9e694b.jpg)

Ok little black guy you exposed your chicken foot

**Comment by Krentelion** [comment]
> Ok little black guy you exposed your chicken foot

What?

**Comment by zeroruka** [comment]
> What?

It's a Chinese meme, read about it [here](https://www.quora.com/What-is-the-meaning-of-the-Chinese-%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E-1). "little black guy" is a direct translation of 小黑子, which refers to haters of 蔡徐坤 (the chinese star shown in the link above).

**Comment by Krentelion** [comment]
> It's a Chinese meme, read about it [here](https://www.quora.com/What-is-the-meaning-of-the-Chinese-%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E-1). "little black guy" is a direct translation of 小黑子, which refers to haters of ‎Cai Xukun ‎(the chinese star shown in the link above).

Ah, okay. Thanks for clarifying.

**Comment by UID-503058116** [comment]
Dear my friend, please accept my sincerest apology. I’m afraid that I can’t complete the mission about the Raiden Shogun Mod, because my vacation is over and I have to go back to school now :( 
I’m so sorry bro.

**Comment by UID-503058116** [comment]
I've made some progress, but overall I need to improve it. Some unexpected difficulties got in the way, such as the weights, the UV editing, and some puzzling shadow errors. I even have to make some new issues for this issue 🤣

**Comment by whiost** [comment]
It doesn't matter bro,maybe someone else will complete this re, I guess .
Anyway,thank you very for your help and kindness.
