### ISSUE TITLE
[REQUEST]有大佬接mod定制吗？技术力要过关

### ISSUE THREAD

**Issue by fengyan11** [zeroruka/GI-Assets#151]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by UID-503058116** [comment]
您好！如果您需要新的 Mod 的话，请直接描述您的要求。如果能附上一些图片辅助说明，那就是最好了。我是 Blender 初学者，如果您有什么 Mod 方面的要求，我会无偿地、尽力地来辅助您。高难度地任务还请您直接发 Request...
**以您当前的标题：**

> [REQUEST]有大佬接mod定制吗？技术力要过关 #151

作为 Request 的内容，我个人觉得，**要受到很好的协助，恐怕是有难度的。**您应该直接表明您的需求，描述它，清晰而简洁地。正如这两句话所说：

Describe the style you'd like
A clear and concise description of what you want it to look like.

Additional context
Add any other context or screenshots about the skin request here.

**Comment by fengyan11** [comment]
求个技术力强的大佬，有偿，有意的加q私聊

**Comment by fengyan11** [comment]
![YO K(X}J X4J %5DJCXG4](https://user-images.githubusercontent.com/107903693/185665824-e652adc5-fe9a-492e-970e-216ead0595a6.png)
如图，希望有大佬能做出这种巨乳mod，细节要足够，尽量要没有bug
