### ISSUE TITLE
[QUESTION]怎么使用

### ISSUE THREAD

**Issue by SHENMOZHIHU** [zeroruka/GI-Assets#155]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by zeroruka** [comment]
https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md

**Comment by UID-503058116** [comment]
已解决的issue 别忘了close
谢谢！仍有疑问的欢迎提出
