### ISSUE TITLE
[BUG]凝光的mod出现撕裂状况

### ISSUE THREAD

**Issue by liarshen** [zeroruka/GI-Assets#157]
**Describe the bug**
![image](https://user-images.githubusercontent.com/67998967/185540945-1f85dc6a-b882-4f1a-862c-c03ca9c0a523.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zeroruka** [comment]
更新你的3DMigoto

**Comment by liarshen** [comment]
> 3DMigoto

好的谢谢大佬！
