### ISSUE TITLE
[REQUEST]宵宫

### ISSUE THREAD

**Issue by Fhjjbiojnt** [zeroruka/GI-Assets#159]
希望用刻晴裸体的底来做宵宫的模型，并保留裙子及部分绷带

**Comment by luoluojialuo** [comment]
使用刻晴模板就没有上衣与腰，除非你能接受左右胸不同形状，也不会保留除了手臂以外的绷带，刻晴模板上半身用上了基本就是奔着全裸去的。或者你等一个既懂改模也懂美术与画贴图的大佬出手做。

**Comment by Fhjjbiojnt** [comment]
那可以做一个刻晴改的全裸吗，感谢

**Comment by holycwww** [comment]
宵宫最初那一版就很好，现在的版本把绳结等饰物去掉了光溜溜的平板一点都不好看

**Comment by luoluojialuo** [comment]
> 宵宫最初那一版就很好，现在的版本把绳结等饰物去掉了光溜溜的平板一点都不好看

那我把blend放上来，你自己改  好吧？文件里有绳结饰物，图层合并导出就行。

**Comment by luoluojialuo** [comment]
[https://github.com/luoluojialuo/GI-Assets/tree/%E7%A7%81%E4%BA%BA/Blend](url)

**Comment by Fhjjbiojnt** [comment]
可以用刻晴改的吗，比较喜欢刻晴的形状

**Comment by luoluojialuo** [comment]
> 可以用刻晴改的吗，比较喜欢刻晴的形状

在尝试，下半身要刻晴形状的立刻可以有，上下都要的没那么快。

**Comment by Fhjjbiojnt** [comment]
谢谢大佬

**Comment by luoluojialuo** [comment]
![20220824020518](https://user-images.githubusercontent.com/107736073/186232070-e0dc87f3-9b62-4145-9cc9-958766d2f6d7.png)

**Comment by Fhjjbiojnt** [comment]
希望下面能不要太凸、胸部大一点，其余的都非常棒

**Comment by Fhjjbiojnt** [comment]
希望下面能不要太凸、胸大一点，其余的都非常棒

**Comment by Fhjjbiojnt** [comment]
可以分享mod和blend档吗
