### ISSUE TITLE
[BUG] A bug with the arm of Ayaka

### ISSUE THREAD

**Issue by whiost** [zeroruka/GI-Assets#161]
**Describe the bug**
There's a bug with the arm of Ayaka

**Screenshots**
![GVR3 J46E0~6D92SX9XJ2N](https://user-images.githubusercontent.com/83504710/185788233-bfd8e0e5-3a84-455c-809f-7baa7894a6b9.png)

**Comment by UID-503058116** [comment]
I think it's also caused by abnormal weights. One of my friend also realized this issue, and he once talked to me about it. He pointed out that it might be a little hard to solve this issue.
