### ISSUE TITLE
[GENERAL]文件里给的琴的mod没有效果，请问是需要修改什么地方吗？

### ISSUE THREAD

**Issue by koerit** [zeroruka/GI-Assets#162]

**Comment by UID-503058116** [comment]
mod本身应该没有问题 请注意以下几个要点：
1. 启动游戏前要先启动3dmigoto loader
2. 3dmigoto的d3dx.ini内需要修改。如果您不记得修改内容，请检查3dm教程README.md

**Comment by koerit** [comment]
@UID-503058116 ，首先感谢您的解答，启动方式和d3dx.ini内的游戏路径修改都是按教程指示进行的，进入游戏按下F10后没有报错，除了琴和罗莎莉亚以外的mod都能正常生效。游戏是简中服的，给这两个角色切换两种服装也没能使mod生效。

**Comment by koerit** [comment]
@luoluojialuo 好的，谢谢您
