### ISSUE TITLE
[REQUEST]能不能做一个把空替换成果体荧的mod？当初脑抽选了哥哥，想看妹妹。

### ISSUE THREAD

**Issue by mlgbqmzzf** [zeroruka/GI-Assets#168]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by fengyan11** [comment]
啊这，就算能换声音也换不了啊，还是男声，不别扭吗？

**Comment by whfie** [comment]
> 

_你这么一说好像更刺激了_

**Comment by liarshen** [comment]
你是在官服使用的吗，不会检测到封号吗，一直不敢用

**Comment by mlgbqmzzf** [comment]
> 你是在官服使用的吗，不会检测到封号吗，一直不敢用

是在官服，已经用了很久了，没有事，而且封也只是封三天。

**Comment by azklkjl** [comment]
在正式服不封？？

**Comment by fushuzhe** [comment]
> 

我也用了一段时间了，问题不大，实在担心又找不到私服的话，就减少使用、少用来打副本深渊啥的吧

**Comment by fushuzhe** [comment]
> 你是在官服使用的吗，不会检测到封号吗，一直不敢用



> 你是在官服使用的吗，不会检测到封号吗，一直不敢用

我也用了一段时间了，问题不大，实在担心又找不到私服的话，就减少使用、少用来打副本深渊啥的吧
