### ISSUE TITLE
[REQUEST] NSFW mod for Raiden, Jean (CN) and Amber (CN)

### ISSUE THREAD

**Issue by Twomuchsurv** [zeroruka/GI-Assets#178]
**Is your skin request related to a problem? Please describe.**
Just a request

**Describe the style you'd like**
A clean nude like the image below, shoes/heels are fine. For amber I think keeping the bunny ear would be nice

**Additional context**
![image_2022-08-29_231736957](https://user-images.githubusercontent.com/112411465/187235274-32dedccb-520a-47e2-b980-6c35d7863832.png)

**Comment by xblk20120425** [comment]
![snap_screen_20220830053017](https://user-images.githubusercontent.com/57083683/187302649-3f936608-ad52-4212-abba-929aed138829.png)
Dilated enough that the uterus can be clearly seen

**Comment by xblk20120425** [comment]
The advanced。

**Comment by shenmo7192** [comment]
Use this
https://www.bilibili.com/video/BV11m4y1o7eS

**Comment by Twomuchsurv** [comment]
Tbh I would want to add Kokomi to the request too, but idk if that's too much lol.
