### ISSUE TITLE
[REQUEST] NSFW mod for Collei

### ISSUE THREAD

**Issue by sincers** [zeroruka/GI-Assets#180]
**Is your skin request related to a problem?
No, Just a request :)
**Describe the style you'd like**
just remove underwear like the image below but with the skirt and keep the other.
**Additional context**
![Collei](https://user-images.githubusercontent.com/112019013/187344030-d28a4659-2b14-4f0a-bd4f-6af857d66c7f.jpg)

**Comment by zeroruka** [comment]
done
