### ISSUE TITLE
妮露

### ISSUE THREAD

**Issue by djjsns** [zeroruka/GI-Assets#182]
<img src="https://user-images.githubusercontent.com/109934183/187373885-2a985fab-b333-496c-ae18-6be583e97397.jpg" width="200"/> <img src="https://user-images.githubusercontent.com/109934183/187374068-b2e3f77e-6447-4f46-99ae-c3b33025fa4f.jpg" width="200"/>
其他mod能正常用

**Comment by zeroruka** [comment]
升级3dmigoto

**Comment by djjsns** [comment]
> 升级3d照片

大佬，能发一下新版3dm吗，或者能说一下在哪下吗，我找不到
