### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Yuye0102** [zeroruka/GI-Assets#183]
![尼禄bug](https://user-images.githubusercontent.com/109961044/187595212-c2b923aa-7749-4e1a-9ff8-acc53e8594ed.png)
为什么其他的模型都没问题，一用妮露的就变成这样···更新了3Dmigo都没有用呀，求大佬解答一下？

**Comment by zeroruka** [comment]
用这个 https://github.com/SilentNightSound/GI-Model-Importer/releases/download/V6.0/3dmigoto-GIMI-for-development.zip

**Comment by Sunben4869** [comment]
大佬，你是用的3.0的割草机吗，在哪获得的，我只有2.8的

**Comment by ygbjhhhj** [comment]
我想问问代码是什么

**Comment by ygbjhhhj** [comment]
我想问问代码是什么

**Comment by ygbjhhhj** [comment]
我想问问代码是什么
