### ISSUE TITLE
[REQUEST] 可以制作那几只萝莉的涩涩mod吗

### ISSUE THREAD

**Issue by CappuCoco** [zeroruka/GI-Assets#187]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by TaoYaoao** [comment]
那几只萝莉咋做？涩不起来。

**Comment by CappuCoco** [comment]
> 那几只萝莉咋做？涩不起来。

都可以涩涩！衣服脱了就行了

**Comment by Hakureitaiga** [comment]
太刑啦，不过真的好像要那几只的涩涩（）

**Comment by zeroruka** [comment]
已经有别人做过了，可以自己去搜搜看。我不会制作萝莉mod。

**Comment by CappuCoco** [comment]
> 已经有别人做过了，可以自己去搜搜看。我不会制作萝莉mod。

求指个路

**Comment by Hakureitaiga** [comment]
可以麻烦大佬指个路嘛〒▽〒 我实在没有找到

**Comment by TaoYaoao** [comment]
https://pan.baidu.com/s/4oC1qM8M

**Comment by TaoYaoao** [comment]
不会做共享链接。。。。麻了，不会用百度网盘

**Comment by TaoYaoao** [comment]
【超级会员V1】通过百度网盘分享的文件：多莉.zip等5个文件
链接:https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r 
提取码:489r
复制这段内容打开「百度网盘APP 即可获取」

**Comment by huaji01** [comment]
> 

大佬，这个mod有出处地址或者作者名吗

**Comment by huaji01** [comment]
> 【超级会员V1】通过百度网盘分享的文件：多莉.zip等5个文件 链接:[https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r ](https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r%C2%A0) 提取码:489r 复制这段内容打开「百度网盘APP 即可获取」

大佬这个mod有出处地址或者作者名吗

**Comment by CappuCoco** [comment]
> 【超级会员V1】通过百度网盘分享的文件：多莉.zip等5个文件 链接:[https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r ](https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r%C2%A0) 提取码:489r 复制这段内容打开「百度网盘APP 即可获取」

我操，谢谢大佬，大佬一生平安，大佬早生贵子

**Comment by Hakureitaiga** [comment]
> 【超级会员V1】通过百度网盘分享的文件：多莉.zip等5个文件 链接:[https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r ](https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r%C2%A0) 提取码:489r 复制这段内容打开「百度网盘APP 即可获取」

谢谢大佬！！十分感谢！:D

**Comment by TaoYaoao** [comment]
没，转载的，我也不知道作者，我找了一圈没找到。

**Comment by Hakureitaiga** [comment]
我找到了，作者是一个叫做tedom的大佬

**Comment by CappuCoco** [comment]
> 我找到了，作者是一个叫做tedom的大佬

在哪可以找到啊，是那个叫gamebanana的网站吗，但是这个网站只有3个模型，而且都与那几只萝莉无关，推特油土鳖等搜出来都是一个机械品牌

**Comment by fushuzhe** [comment]
> 【超级会员V1】通过百度网盘分享的文件：多莉.zip等5个文件 链接:[https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r ](https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r%C2%A0) 提取码:489r 复制这段内容打开「百度网盘APP 即可获取」

终于找到资源了，感谢大佬，好人一生平安

**Comment by 1091606207** [comment]
> 【超级会员V1】通过百度网盘分享的文件：多莉.zip等5个文件 链接:[https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r ](https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r%C2%A0) 提取码:489r 复制这段内容打开「百度网盘APP 即可获取」

大佬能再发一次吗 链接失效了

**Comment by fushuzhe** [comment]
> > 【超级会员V1】通过百度网盘分享的文件：多莉.zip等5个文件 链接:[https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r ](https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r%C2%A0) 提取码:489r 复制这段内容打开「百度网盘APP 即可获取」
> 
> 大佬能再发一次吗 链接失效了

链接：https://pan.baidu.com/s/1nLqTBRb45GbQKNqmGwldJQ 
提取码：lmw6
就一天就没了？？？保险起见我又套了一层，应该都能看懂

**Comment by LTSY123** [comment]
> > > 【超级会员V1】通过百度网盘分享的文件：多莉.zip等5个文件 链接:[https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r ](https://pan.baidu.com/s/1wrqb9yVDKLEnjIWCDg2lwQ?pwd=489r%C2%A0) 提取码:489r 复制这段内容打开「百度网盘APP 即可获取」
> > 
> > 
> > 大佬能再发一次吗 链接失效了
> 
> 链接：https://pan.baidu.com/s/1nLqTBRb45GbQKNqmGwldJQ 提取码：lmw6 就一天就没了？？？保险起见我又套了一层，应该都能看懂

感谢分享 建议去掉前面的https://pan.baidu.com之留后面的 这样估计会保留时间更长

**Comment by TaoYaoao** [comment]
哦豁，现在除了男性角色，女性角色被脱了个遍了，离谱的是，派蒙都没放过，好家伙，太可怕了

**Comment by LTSY123** [comment]
> 哦豁，现在除了男性角色，女性角色被脱了个遍了，离谱的是，派蒙都没放过，好家伙，太可怕了

菲谢尔的mod失效 辛焱跟北斗是没的 派蒙的mod你在哪里找的

**Comment by TaoYaoao** [comment]
这两不是都有吗？黑妹和北斗

**Comment by fushuzhe** [comment]
> 这两不是都有吗？黑妹和北斗

全都有？！大佬可以发一下链接吗，派蒙北斗辛焱，还有罗莎的。
男角色的好像确实没有？不太清楚，男角色裸80%，或者加腹肌胸肌应该比较容易，但是那一根要做出来就......

**Comment by LTSY123** [comment]
> 这两不是都有吗？黑妹和北斗

还有吗？

**Comment by Gen-LLL** [comment]
> 这两不是都有吗？黑妹和北斗

大佬在哪呢，求指路

**Comment by TaoYaoao** [comment]
在那个banana的网站上，都有啊

**Comment by LTSY123** [comment]
这网站不太行

**Comment by YuhLae** [comment]
> 在那个banana的网站上，都有啊

找不到你说的那几个啊？

**Comment by fushuzhe** [comment]
> 在那个banana的网站上，都有啊

这个网站我不知道诶，可以发个链接吗
