### ISSUE TITLE
[REQUEST] kokomi NSFW skin request with model file

### ISSUE THREAD

**Issue by shenmo7192** [zeroruka/GI-Assets#188]
Model file is here

https://smutba.se/project/32902/

**Comment by LTSY123** [comment]
链接错误

**Comment by shenmo7192** [comment]
> 链接错误

我这里看起来很正常啊

**Comment by shenmo7192** [comment]
> 链接错误

https://smutba.se/project/file/download/47951/ams1/
直链

**Comment by LTSY123** [comment]
> > 链接错误
> 
> https://smutba.se/project/file/download/47951/ams1/ 直链

正常了

**Comment by shenmo7192** [comment]
> > > 链接错误
> > 
> > 
> > https://smutba.se/project/file/download/47951/ams1/ 直链
> 
> 正常了

模型很色诶(

**Comment by shenmo7192** [comment]
@zeroruka 所以是已拒绝是吗(

**Comment by zeroruka** [comment]
也不是，这星期有时间就做

**Comment by shenmo7192** [comment]
> 也不是，这星期有时间就做

跪谢！

**Comment by zeroruka** [comment]
做好了

**Comment by shenmo7192** [comment]
> 做好了

Chinese Style Hero
中国式英雄
