### ISSUE TITLE
[BUG]妮露的上半身模型有问题

### ISSUE THREAD

**Issue by mclaren-bit** [zeroruka/GI-Assets#189]
[**Describe](![K)8I2`R4IBMLPZ~RIHG9@SH](https://user-images.githubusercontent.com/76802267/189474286-ff8bf81a-7a0c-4f51-ad04-d6523ced8528.jpg)) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zeroruka** [comment]
用这个 https://github.com/SilentNightSound/GI-Model-Importer/releases/download/V6.0/3dmigoto-GIMI-for-development.zip

**Comment by 1008611wu** [comment]
更了最新的3dm，尼禄还是一坨糊的

**Comment by mclaren-bit** [comment]
> 用这个 https://github.com/SilentNightSound/GI-Model-Importer/releases/download/V6.0/3dmigoto-GIMI-for-development.zip

亲测有效，谢谢
