### ISSUE TITLE
怎么把模型换成3dm

### ISSUE THREAD

**Issue by djjsns** [zeroruka/GI-Assets#192]
我下了别人的模型，想换成3dm
有大佬教一下，或者发个教程吗，尽量是中文
https://smutba.se/?universe_tag=31
在这个网站里面下的

**Comment by djjsns** [comment]
[
![9L$H)@7_8D3T%AGEHZL~MM4](https://user-images.githubusercontent.com/109934183/189529699-96351e81-46b5-47c2-81ac-4aa75eaf1bf4.png)
](url)

**Comment by liarshen** [comment]
同求教程

**Comment by djjsns** [comment]
> 同求教程

有了兄弟，我从dc上联系到了大佬本人，以下是大佬发的教程，但我也只是一知半解

https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97-3dmigoto-blender-%E6%8F%92%E4%BB%B6
https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/CN_MonaWalkthrough.md

**Comment by djjsns** [comment]
https://www.youtube.com/watch?v=fBIlT1o1Jsc

**Comment by liarshen** [comment]
兄弟整成功了不 我还在摸索

**Comment by djjsns** [comment]
> 兄弟整成功了不 我还在摸索

按照教程做完了，都是不知道为什么没有效果

**Comment by liarshen** [comment]
大佬完成了不

**Comment by djjsns** [comment]
> 大佬完成了不
莫娜去帽子只能在国际服生效，
要做大佬们那种换完整个身体，起码需要两天，在有指导的情况下。

**Comment by liarshen** [comment]
好的 感谢提醒

**Comment by liarshen** [comment]
> > 好的 感谢提醒
> 
> 
> 
> 兄弟，如果你要试着做我建议还是加dc找大佬指导，自己做的话我感觉太难了
> 
> https://discord.gg/agmg
> 
> 这是dc的链接

非常感谢兄弟，我闲下来了试试看

**Comment by xiao1iu** [comment]
> 



> > 同求教程
> 
> 有了兄弟，我从dc上联系到了大佬本人，以下是大佬发的教程，但我也只是一知半解
> 
> https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97-3dmigoto-blender-%E6%8F%92%E4%BB%B6 https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/CN_MonaWalkthrough.md

大佬，能问下怎么不挂梯子通过discord服务器机器人验证的吗，求教

**Comment by djjsns** [comment]
> > 
> 
> > > 同求教程
> > 
> > 
> > 有了兄弟,我从哥伦比亚特区上联系到了大佬本人,以下是大佬发的教程,但我也只是一知半解
> > [https://github . com/silentnighsound/GI-Model-Importer/blob/main/CN _ readme . MD # % E5 % AE % 89% E8 % A3 % 85% E6 % 8C % 87% E5 % 8D % 97-3d migo to-blender-% E6 % 8F % 92% E4 % BB % B6](https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97-3dmigoto-blender-%E6%8F%92%E4%BB%B6) [https://github . com/silentnighsound/GI-Model-Importer/blob/main/Guides/CN _ Mona walk through . MD](https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/CN_MonaWalkthrough.md)
> 
> 大佬,能问下怎么不挂梯子通过不调和服务器机器人验证的吗,求教

这个是梯子的问题，我一开始也不行，换了个梯子就好了，你可以试试，手机的免费梯子还是有不少的

**Comment by xiao1iu** [comment]
> > > 
> > 
> > 
> > > > 同求教程
> > > 
> > > 
> > > 有了兄弟,我从哥伦比亚特区上联系到了大佬本人,以下是大佬发的教程,但我也只是一知半解
> > > [https://github . com/silentnighsound/GI-Model-Importer/blob/main/CN _ readme . MD # % E5 % AE % 89% E8 % A3 % 85% E6 % 8C % 87% E5 % 8D % 97-3d migo to-blender-% E6 % 8F % 92% E4 % BB % B6](https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97-3dmigoto-blender-%E6%8F%92%E4%BB%B6) [https://github . com/silentnighsound/GI-Model-Importer/blob/main/Guides/CN _ Mona walk through . MD](https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/CN_MonaWalkthrough.md)
> > 
> > 
> > 大佬,能问下怎么不挂梯子通过不调和服务器机器人验证的吗,求教
> 
> 这个是梯子的问题，我一开始也不行，换了个梯子就好了，你可以试试，手机的免费梯子还是有不少的

好的，谢谢，非常感谢
