### ISSUE TITLE
[REQUEST] Collei Short Skirt With Cape

### ISSUE THREAD

**Issue by Julienraptor01** [zeroruka/GI-Assets#193]
**Is your skin request related to a problem? Please describe.**
Collei Short Skirt is great but i like the cape

**Describe the style you'd like**
Simple merge of [Short Skirt](https://github.com/zeroruka/GI-Assets/tree/main/Mods/3Dmigoto/Mods%20(nsfw)/Collei/ShortSkirt) and [With Cape](https://github.com/zeroruka/GI-Assets/tree/main/Mods/3Dmigoto/Mods%20(nsfw)/Collei/WithCape)

**Additional context**
Thanks already for these mods

**Comment by zeroruka** [comment]
Hi! Can you try this mod? [ColleiShortSkirtWithCape.zip](https://cdn.discordapp.com/attachments/864124722467307541/1026860254539034664/ColleiMod.zip) I have not tested it yet, please tell me if there's any issues.

**Comment by Julienraptor01** [comment]
Seems to work perfectly thanks
