### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by p0sha** [zeroruka/GI-Assets#198]
Why can't I download the entire folder with the mod, but can I download individual files from the folder. that is, I need to assemble the folder from separate files myself?

**Comment by TaoYaoao** [comment]
请使用https://minhaskamal.github.io/DownGit/#/home也就是在文件夹首页的工具进行下载，直接复制mod文件链接就行

> 为什么我不能用 mod 下载整个文件夹，但我可以从文件夹中下载单个文件。也就是说，我需要自己从单独的文件中组装文件夹吗？

**Comment by LTSY123** [comment]
> 请使用https://minhaskamal.github.io/DownGit/#/home 也就是在文件夹首页的工具进行下载，直接复制mod文件链接就行
> 
> > 为什么我不能用 mod 下载整个文件夹，但我可以从文件夹中下载单个文件。也就是说，我需要自己从单独的文件中组装文件夹吗？

建议用油猴插件下载 那个可以单独文件夹下载 这不是bug
