### ISSUE TITLE
[BUG]妮露，显示问题

### ISSUE THREAD

**Issue by fushuzhe** [zeroruka/GI-Assets#201]
（之前科莱的问题解决了，更新了3dm）
![原神 2022_9_24 19_39_45](https://user-images.githubusercontent.com/98632125/192097025-09f43198-82c9-4680-9f83-f49b7ef3ce1a.png)
但是妮露的出问题了

**Comment by djjsns** [comment]
https://github.com/SilentNightSound/GI-Model-Importer/releases
这个是新版3dm

**Comment by fushuzhe** [comment]
> https://github.com/SilentNightSound/GI-Model-Importer/releases 这个是新版3dm

谢谢，科莱的问题解决了

**Comment by zeroruka** [comment]
还是不行？

**Comment by fushuzhe** [comment]
> 还是不行？

当时换了新版3dm的还是不行，现在没有妮露了我没法验证，所以我先关闭这个issue，之后再说吧
