### ISSUE TITLE
[GENERAL]大佬这个怎么解决啊，一直加载不出

### ISSUE THREAD

**Issue by MisakaMikoto2333** [zeroruka/GI-Assets#202]
![image](https://user-images.githubusercontent.com/68831929/190442576-ce3381d7-b58a-4325-9b14-2004d9f4c1fe.png)

**Comment by TaoYaoao** [comment]
把教程再看一遍吧。我记得好像有个搅拌机插件。不知道是不是这个的原因

**Comment by LTSY123** [comment]
路径不对，改路径，你原神放C盘？
C盘战士
![Uploading 1f86503e99eeddbe.jpg…]()

**Comment by MisakaMikoto2333** [comment]
> 把教程再看一遍吧。我记得好像有个搅拌机插件。不知道是不是这个的原因

解决了，这程序有个问题，原神必须要全屏才能注入，不是全屏就会这样，把我整麻了
