### ISSUE TITLE
[GENERAL]

### ISSUE THREAD

**Issue by yuki1002x** [zeroruka/GI-Assets#203]
有无大佬说说为什么打开之后不能用啊？打开游戏这个页面就被关了，游戏里什么都没改
![111112](https://user-images.githubusercontent.com/76468701/190486720-7213553d-a69e-4e7b-ac98-c5fbdb2ca087.png)

**Comment by 2589307976** [comment]
打开游戏这个界面被关了，说错了

**Comment by LTSY123** [comment]
mod加载器没下载完整吧

**Comment by yuki1002x** [comment]
> 
网友给的，我下了新版本的，能用了，但是没声音，网友给的mod也有好多不能用

**Comment by LTSY123** [comment]
> > 
> 
> 网友给的，我下了新版本的，能用了，但是没声音，网友给的mod也有好多不能用

这里的mod都能用，除了菲谢尔的

**Comment by MisakaMikoto2333** [comment]
我也是用不了，请问最新版本是哪个

**Comment by yuki1002x** [comment]
> 我也用不了，请问最新版本是哪个

https://github.com/SilentNightSound/GI-Model-Importer/releases
