### ISSUE TITLE
[GENERAL]最近自学自制mod，遇到不少问题

### ISSUE THREAD

**Issue by Pppppppi** [zeroruka/GI-Assets#206]
大佬有交流群之类的嘛，有偿也可以

**Comment by Sunben4869** [comment]
都是在discord上面认识大佬的，Anime Game Modding Group上应该联系得到大佬

**Comment by Pppppppi** [comment]
> 都是在discord上面认识大佬的，Anime Game Modding Group上应该联系得到大佬

好的感谢

**Comment by shenmo7192** [comment]
https://discord.gg/gfhrpkRahr
