### ISSUE TITLE
[GENERAL]请问如何把琴原皮的mod转移到闲替皮肤上啊

### ISSUE THREAD

**Issue by YuhLae** [zeroruka/GI-Assets#207]
RT 想在过场动画里看到那个mod

**Comment by manhongfeiqing** [comment]
过场动画的mod是自动替换的，只是需要对应的mod，琴的皮肤有三个，过场动画中是否能替换主要看琴是不是穿了具有对于mod的皮肤，比如你未安装夏装皮肤，那么在琴身着夏装的过场动画中就不会发生替换

**Comment by YuhLae** [comment]
> 

可能我说的不是很明白，我的意思是想把和谐前的原皮对应的mod转移到和谐后出的闲替衣装上，因为打了那个mod只会反映在原皮上，而过场动画目前都被替换为了闲替衣装，无法体现。所以我在想能不能把那个mod改一下变成打在闲替衣装上

**Comment by YuhLae** [comment]
> 过场动画的mod是自动替换的，只是需要对应的mod，琴的皮肤有三个，过场动画中是否能替换主要看琴是不是穿了具有对于mod的皮肤，比如你未安装夏装皮肤，那么在琴身着夏装的过场动画中就不会发生替换



> 过场动画的mod是自动替换的，只是需要对应的mod，琴的皮肤有三个，过场动画中是否能替换主要看琴是不是穿了具有对于mod的皮肤，比如你未安装夏装皮肤，那么在琴身着夏装的过场动画中就不会发生替换

而且我现在找不太到本就基于琴闲替衣装那个皮肤的mod

**Comment by shenmo7192** [comment]
https://github.com/SilentNightSound/GI-Model-Importer-Assets
在这里找到琴闲替的文件，利用blender https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md 到处一个原版的闲替的mod,然后把原版的mod贴图文件替换到闲替mod中
