### ISSUE TITLE
去掉久岐忍的裤子就行

### ISSUE THREAD

**Issue by 1008611wu** [zeroruka/GI-Assets#209]
可以尽量完成吗

**Comment by Gen-LLL** [comment]
同求一个忍的皮肤~

**Comment by 2855743931** [comment]
> ![20221018204341](https://user-images.githubusercontent.com/107736073/196432973-ff6fda7a-12cd-4bee-98c5-2677cc41e1e7.png)就这样吧 忍这一身也没什么好脱的了，看点不多。

主要是想看她光着屁股就行hhh

**Comment by luoluojialuo** [comment]
> 

屁股就光了中间一半，两边没有做。
