### ISSUE TITLE
the Rosaria Mod(nsfw) doesn't work

### ISSUE THREAD

**Issue by olyvande** [zeroruka/GI-Assets#211]
I use the GI and put mod in it.But in game it doesn't work.I don't know it's my fault or the mod?

**Comment by olyvande** [comment]
I'll use another PC and try it again

**Comment by zeroruka** [comment]
You should just use the mod posted in [agmg](https://discord.gg/agmg) since the rosaria mod here is really old and only modifies the texture

https://discord.com/channels/971945032552697897/995556219303510026/1028621921962709072

**Comment by olyvande** [comment]
Sadly I can't read the history message in agmg.Do you save them?

**Comment by zeroruka** [comment]
https://cdn.discordapp.com/attachments/995556219303510026/1028621920331124817/RosariaAltsMod.rar
