### ISSUE TITLE
还有最后版本的3dm的压缩包吗，如果没保存的话我有保存，就是模组的

### ISSUE THREAD

**Issue by 729237168** [zeroruka/GI-Assets#234]
还有最后版本的3dm的压缩包吗，如果没保存的话我有保存，就是模组的

**Comment by manhongfeiqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zeroruka** [comment]
被dmca的我过几天会上传到别处

**Comment by zeroruka** [comment]
https://gitlab.com/zeroruka/AGM
