### ISSUE TITLE
[GENERAL] Layla is missing

### ISSUE THREAD

**Issue by ARHCOS** [zeroruka/GI-Assets#237]
I think you forgot about her existence can you add her please ?

**Comment by manhongfeiqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zeroruka** [comment]
added

**Comment by ARHCOS** [comment]
thanks
