### ISSUE TITLE
I cant download it, download just stops automatic on half way please help

### ISSUE THREAD

**Issue by WIZARDZ007** [zeroruka/GI-Assets#238]
I cant download it, download just stops automatic on half way please help

**Comment by manhongfeiqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WIZARDZ007** [comment]
Thx but download worked😅and i dont understand chinese sry
