### ISSUE TITLE
[BUG] Layla Materials missing?

### ISSUE THREAD

**Issue by KryptoSynth** [zeroruka/GI-Assets#242]
**Describe the bug**
Layla doesn't have material files.

**To Reproduce**
Go to Layla folder.

**Expected behavior**
There should be a Materials folder like all the other characters.

**Screenshots**
![SS_2023-07-29_22-15-51](https://github.com/zeroruka/GI-Assets/assets/109325672/abb4e99e-d5d0-416e-adca-08514deefdea)

**Additional context**
None.

**Comment by manhongfeiqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yarik0chka** [comment]
Hello, materials have been added in https://github.com/zeroruka/GI-Assets/commit/e12ad68f753f61ad5c14da2279b749fbcd34684d
