### ISSUE TITLE
Layla Material File (.JSON Materials) Missing

### ISSUE THREAD

**Issue by MacabreVoid** [zeroruka/GI-Assets#246]
Layla Material File Missing
The Material Folder for Layla is missing for some reason, as opposed to other characters

To Reproduce
1. Go to GI-Assets
2. Click on Models
3. Click on Character
4. Click on Layla
5. No Materials Folder
6. 
![image](https://github.com/zeroruka/GI-Assets/assets/148668301/327f69b4-80bd-400d-956d-9b7df9e2caa4)

I expected there to be materials for Layla, however there is no material folder

**Comment by manhongfeiqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yarik0chka** [comment]
Hello, materials have been added in https://github.com/zeroruka/GI-Assets/commit/e12ad68f753f61ad5c14da2279b749fbcd34684d

**Comment by manhongfeiqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
