### ISSUE TITLE
求一个安柏的3migoto的mod，最好能去掉热裤，非常感谢

### ISSUE THREAD

**Issue by fengyan11** [zeroruka/GI-Assets#59]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by abyss1103** [comment]
3dmigoto和skin能一起用吗

**Comment by WQ3465802** [comment]
> 3dmigoto和skin能一起用吗

3dmigoto应该可以直接使用skin

**Comment by abyss1103** [comment]
> > 3dmigoto和skin能一起用吗
> 
> 3dmigoto应该可以直接使用skin

是要把文件里的全都下载放进去吗

**Comment by abyss1103** [comment]
> > 3dmigoto和skin能一起用吗
> 
> 3dmigoto应该可以直接使用skin

怎么直接下整个模组文件，我都只能点进去一个个下
