### ISSUE TITLE
[REQUEST] 优菈 提议增加一个保留胸部装饰的版本

### ISSUE THREAD

**Issue by shenmo7192** [zeroruka/GI-Assets#72]
**Describe the style you'd like**
相比于原版衣装，在胸部的很多细节用奈子替换就显得有些不足。可以考虑把胸部装饰保留

**Additional context**
夜兰皮肤的似乎也有类似的问题

**Comment by shenmo7192** [comment]
![图片](https://user-images.githubusercontent.com/47873776/178658873-f165e5d4-76bb-4a99-bbc6-e61ad8eca6c1.png)
从背后看是比较完美的

**Comment by abyss1103** [comment]
现在zeroka专注于做mod，贴图已经不做了，自学吧

**Comment by abyss1103** [comment]
教程都有很简单的

**Comment by shenmo7192** [comment]
> 在wiki里

既然你改了可以分享一下吗(

**Comment by abyss1103** [comment]
> > 在wiki里
> 
> 既然你改了可以分享一下吗(

我没改，我只改了个光腿的在其他解决的问题里自己看。我觉得这样够了以后zeroruka会出更好的
