### ISSUE TITLE
[REQUEST]求一个全裸的旅行者

### ISSUE THREAD

**Issue by l-fog** [zeroruka/GI-Assets#85]
如题

**Comment by fengyan11** [comment]
> 如题

加我一个，要荧的不要空的

**Comment by abyss1103** [comment]
爷不能留衣服?自己不给自己衣服是吧🤔😂

**Comment by fengyan11** [comment]
> 爷不能留衣服?自己不给自己衣服是吧🤔😂

爷馋爷自己身子[dog]

**Comment by yejunjie10311031** [comment]
我倒是做过空的
![travellerboy-2](https://user-images.githubusercontent.com/62139629/179655505-9c7c8a55-9046-4c62-b05a-cab16ece0ede.png)
![travellerboy-3](https://user-images.githubusercontent.com/62139629/179655519-ddcf4001-4249-45b6-b5fc-140e94735943.png)
![travellerboy-1](https://user-images.githubusercontent.com/62139629/179655556-55197f7d-7c04-4be4-ae38-fe28f5552009.png)

**Comment by abyss1103** [comment]
> 我倒是做过空的 ![travellerboy-2](https://user-images.githubusercontent.com/62139629/179655505-9c7c8a55-9046-4c62-b05a-cab16ece0ede.png) ![travellerboy-3](https://user-images.githubusercontent.com/62139629/179655519-ddcf4001-4249-45b6-b5fc-140e94735943.png) ![travellerboy-1](https://user-images.githubusercontent.com/62139629/179655556-55197f7d-7c04-4be4-ae38-fe28f5552009.png)

这里面做男的真那啥

**Comment by abyss1103** [comment]
特别奇怪

**Comment by iris10086** [comment]
荧的发PR了。等合并。

**Comment by shenmo7192** [comment]
已经合并，请关闭此issue

**Comment by shenmo7192** [comment]
> > 我倒是做过空的 ![travellerboy-2](https://user-images.githubusercontent.com/62139629/179655505-9c7c8a55-9046-4c62-b05a-cab16ece0ede.png) ![travellerboy-3](https://user-images.githubusercontent.com/62139629/179655519-ddcf4001-4249-45b6-b5fc-140e94735943.png) ![travellerboy-1](https://user-images.githubusercontent.com/62139629/179655556-55197f7d-7c04-4be4-ae38-fe28f5552009.png)
> 
> 这里面做男的真那啥

可以在另一个仓库发

https://github.com/yejunjie10311031/GI-Assets-homo

男性的mod也是有需求的其实(

并不是只有男玩家在玩

不过感觉有点粗糙啊
