### ISSUE TITLE
可不可以尽量照着刻晴的下面去做

### ISSUE THREAD

**Issue by djjsns** [zeroruka/GI-Assets#99]
有一些突出或者内凹看着更真，我不知道难度怎么样，我是外行，就当提个建议
![20220725011157](https://user-images.githubusercontent.com/109934183/180705569-e814ecd3-d4eb-4065-9ea1-a375165ed3f4.png)
![20220724013603](https://user-images.githubusercontent.com/109934183/180705576-2c72eef8-ca9d-4499-8dac-74ff6e1e9ee3.png)

**Comment by djjsns** [comment]
![Uploading 20220725021748.png…]()

**Comment by abyss1103** [comment]
你都发多少请求了？要说的话请在同一个帖子里说完

**Comment by djjsns** [comment]
![Uploading 20220725020824.png…]()

**Comment by djjsns** [comment]
> 

抱歉，以后会注意的

**Comment by fengyan11** [comment]
刻晴的mod太赞了，多了些细节，要是以后的mod也有这么好看就好了，zeroruka大佬nb

**Comment by 1008611wu** [comment]
这个mod跟甘雨那个一样在阴处，皮肤非常白，跟脸色差非常大

**Comment by fengyan11** [comment]
> 这个mod跟甘雨那个一样在阴处，皮肤很白，跟脸色差很大
这个倒是小问题，无伤大雅

**Comment by abyss1103** [comment]
> 刻晴的mod太赞了，多了些细节，要是以后的mod也有这么好看就好了，zeroruka大佬nb

我觉得把黑丝加回来就更好了

**Comment by iris10086** [comment]
> 有一些突出或者内凹看着更真，我不知道难度怎么样，我是外行，就当提个建议 ![20220725011157](https://user-images.githubusercontent.com/109934183/180705569-e814ecd3-d4eb-4065-9ea1-a375165ed3f4.png) ![20220724013603](https://user-images.githubusercontent.com/109934183/180705576-2c72eef8-ca9d-4499-8dac-74ff6e1e9ee3.png)
问一下，这是在哪里拍的。

**Comment by djjsns** [comment]
> > 有一些突出或者内凹看着更真，我不知道难度怎么样，我是外行，就当提个建议 ![20220725011157](https://user-images.githubusercontent.com/109934183/180705569-e814ecd3-d4eb-4065-9ea1-a375165ed3f4.png) ![20220724013603](https://user-images.githubusercontent.com/109934183/180705576-2c72eef8-ca9d-4499-8dac-74ff6e1e9ee3.png)
> > 问一下，这是在哪里拍的。

灵渠关随便找个窗口，不过我用了反虚化的软件
![Uploading 20220725010131.png…]()

**Comment by iris10086** [comment]
看不见，添加照片的时候。等他加载完再上传。
没加载完会有uploading字样。
另外，反虚化软件有嘛？

**Comment by djjsns** [comment]
> 

![20220724012814](https://user-images.githubusercontent.com/109934183/180905632-bf54df8d-3888-4a92-9e14-43d929f4171d.png)

**Comment by abyss1103** [comment]
> 看不见，添加照片的时候。等他加载完再上传。 没加载完会有uploading字样。 另外，反虚化软件有嘛？

我想知道你制作的模型仅仅只是在blender里修改了模型导出就好了吗，不需要寻找缓冲区和着色器吗

**Comment by abyss1103** [comment]
主要是下面的缓冲区和着色器什么实在麻烦，都有点不想搞了

**Comment by abyss1103** [comment]
> 看不见，添加照片的时候。等他加载完再上传。 没加载完会有uploading字样。 另外，反虚化软件有嘛？

或者说能详细说说您的制作过程吗

**Comment by iris10086** [comment]
> > 看不见，添加照片的时候。等他加载完再上传。 没加载完会有uploading字样。 另外，反虚化软件有嘛？
> 
> 或者说能详细说说您的制作过程吗


我的参照的教程、模型和贴图都来自[这个项目](https://github.com/SilentNightSound/GI-Model-Importer)。
里面有大佬写的中文教程。推荐观看。

模型修改，再导入挺简单的。

这几天换模型参照的[Genshin Impact model Importing with 3dmigoto - Tutorial](https://www.youtube.com/watch?v=7ijMOjhEvBw&t=1519s)这个视频的流程。

**Comment by abyss1103** [comment]
> 
我知道这个教程。您仅仅只是修改了模型而已吗？教程里不是说还要寻找缓冲区和着色器，然后创建ini文件套入代码等操作吗？

**Comment by abyss1103** [comment]
> > > 看看，照片的时候。等他加载完再上传。没添加完继续上传字样。另外，反虚化软件有嘛？
> > 
> > 
> > 或者说能详细说你的制作过程吗
> 
> 我的参照的教程、模型和贴图都来自[GI-Model-Importer](https://github.com/SilentNightSound/GI-Model-Importer)这个项目。 里面有大佬写的中文教程。推荐观看。
> 
> 模型修改，再导入挺简单的。
> 
> 这几天换模型参照的[Genshin Impact model Importing with 3dmigoto - Tutorial](https://www.youtube.com/watch?v=7ijMOjhEvBw&t=1519s)这个视频的流程。

我大致看了视频，如果我想保留角色本身的衣服，仅仅只把甘雨的胸与缝 缝合上去的话，可以在一开始只保留甘雨的胸和缝吗（其他的都删除）？

**Comment by abyss1103** [comment]
![屏幕截图 2022-07-26 213335](https://user-images.githubusercontent.com/107688386/181018807-791b4727-e47c-4621-b53d-5abd92bf7d14.png)
理想状态下，只保留了胸部可以继续进行视频里的操作吗？

**Comment by iris10086** [comment]
> > 
> 
> 我知道这个教程。您仅仅只是修改了模型而已吗？教程里不是说还要寻找缓冲区和着色器，然后创建ini文件套入代码等操作吗？

在模型文件里有该模型对应的hash.json。
还有python脚本。
我们只用修改模型之后按插件导出即可生成Mod文件夹。

**Comment by iris10086** [comment]
> > > > 看看，照片的时候。等他加载完再上传。没添加完继续上传字样。另外，反虚化软件有嘛？
> > > 
> > > 
> > > 或者说能详细说你的制作过程吗
> > 
> > 
> > 我的参照的教程、模型和贴图都来自[GI-Model-Importer](https://github.com/SilentNightSound/GI-Model-Importer)这个项目。 里面有大佬写的中文教程。推荐观看。
> > 模型修改，再导入挺简单的。
> > 这几天换模型参照的[Genshin Impact model Importing with 3dmigoto - Tutorial](https://www.youtube.com/watch?v=7ijMOjhEvBw&t=1519s)这个视频的流程。
> 
> 我大致看了视频，如果我想保留角色本身的衣服，仅仅只把甘雨的胸与缝 缝合上去的话，可以在一开始只保留甘雨的胸和缝吗（其他的都删除）？

需要修改甘雨胸部模型的权重。相同部位名称相同。

**Comment by iris10086** [comment]
我一般少女使用甘雨的模型，成女使用九条的模型。

**Comment by abyss1103** [comment]
行，明天我试试看，成女的话希望zeroruka把刻晴的Blender格式文件放入，我觉得八重得重做。少女我用芭芭拉，感觉甘雨的小了点哈哈哈

**Comment by abyss1103** [comment]
脚本什么的还是得修改的咯

**Comment by abyss1103** [comment]
> 我一般少女使用甘雨的模型，成女使用九条的模型。

新创建的权重需要定位吗，还是说仅仅创建完就行

**Comment by iris10086** [comment]
1. 八重我重做了。用甘雨胸部换的。下体也弄了一下。添了个肚脐。
2. 不太明白新创建的是啥意思。就用现有的模型替换就行，高级的我也不会整。模型上回这次定点组和权重，不要动他。
3. 权重比例不一样应该不影响。我还没遇到过此类问题。今天重做了八重和申鹤，都没问题。

**Comment by iris10086** [comment]
1. 八重我重做了。用甘雨胸部换的。下体也弄了一下。添了个肚脐。
2. 不太明白新创建的是啥意思。就用现有的模型替换就行，高级的我也不会整。模型上回这次定点组和权重，不要动他。
3. 权重比例不一样应该不影响。我还没遇到过此类问题。今天重做了八重和申鹤，都没问题。我之前做神里的时候，改了一下权重就出bug了。我也不懂什么原理，估计得学unity。

**Comment by fengyan11** [comment]
> 1. 八重我重做了。用甘雨胸部换的。下体也弄了一下。添了个肚脐。
> 2. 不太明白新创建的是啥意思。就用现有的模型替换就行，高级的我也不会整。模型上回这次定点组和权重，不要动他。
> 3. 权重比例不一样应该不影响。我还没遇到过此类问题。今天重做了八重和申鹤，都没问题。

大佬能不能用刻晴的模型做一个荧的mod，求求了

**Comment by iris10086** [comment]
这不巧了，我第一次换模型就是做旅行者。
结果不知道哪里出bug了。计划就搁浅了。
等我过几天再试试。
![荧柱擎天](https://user-images.githubusercontent.com/93846901/181044575-c9fa6fdc-d98b-4f10-a844-ac699071202a.jpg)

**Comment by iris10086** [comment]
而且我也不太会从buffer里找模型。
没有模型用估计也只有用甘雨的。
等我弄一下新神子你看看行不行。

**Comment by hxhxzd** [comment]
> 而且我也不太会从buffer里找模型。 没有模型用估计也只有用甘雨的。 等我弄一下新神子你看看行不行。

buffer就是Github里面的那个吗如果不是可以讲一下吗，我小白想试试诶嘿

**Comment by iris10086** [comment]
> > 而且我也不太会从buffer里找模型。 没有模型用估计也只有用甘雨的。 等我弄一下新神子你看看行不行。
> 
> buffer就是Github里面的那个吗如果不是可以讲一下吗，我小白想试试诶嘿

可以从buffer提取模型，但是非常麻烦。
[SilentNightSound](https://github.com/SilentNightSound)大佬做了脚本，让我们快捷的实现导出功能，也替我们导出了模型。

**Comment by fengyan11** [comment]
> > > 没有模型用估计也用甘雨的。 等我弄一下新神子你看看行里就不行了。
> > 
> > 
> > buffer就是Github里面的那个如果不是可以讲一下吗，我小白想试试看吗
> 
> SilentNightSound大佬实现了脚本，让我们快捷的实现导出功能，也替我们导出了事务模型 [。](https://github.com/SilentNightSound)

那荧的mod有着落了？我都等了好久了

**Comment by iris10086** [comment]
> > > > 没有模型用估计也用甘雨的。 等我弄一下新神子你看看行里就不行了。
> > > 
> > > 
> > > buffer就是Github里面的那个如果不是可以讲一下吗，我小白想试试看吗
> > 
> > 
> > SilentNightSound大佬实现了脚本，让我们快捷的实现导出功能，也替我们导出了事务模型 [。](https://github.com/SilentNightSound)
> 
> 那荧的mod有着落了？我都等了好久了

要是权重不出错，昨天应该就出了。

**Comment by abyss1103** [comment]
> > > > > 没有模型用估计也用甘雨的。 等我弄一下新神子你看看行里就不行了。
> > > > 
> > > > 
> > > > buffer就是Github里面的那个如果不是可以讲一下吗，我小白想试试看吗
> > > 
> > > 
> > > SilentNightSound大佬实现了脚本，让我们快捷的实现导出功能，也替我们导出了事务模型 [。](https://github.com/SilentNightSound)
> > 
> > 
> > 那荧的mod有着落了？我都等了好久了
> 
> 要是权重不出错，昨天应该就出了。

主要很多角色只用甘雨和九条的替换多莉看起来会很怪，不如放着学习胸部建模

**Comment by abyss1103** [comment]
> > > > > 没有模型用估计也用甘雨的。 等我弄一下新神子你看看行里就不行了。
> > > > 
> > > > 
> > > > buffer就是Github里面的那个如果不是可以讲一下吗，我小白想试试看吗
> > > 
> > > 
> > > SilentNightSound大佬实现了脚本，让我们快捷的实现导出功能，也替我们导出了事务模型 [。](https://github.com/SilentNightSound)
> > 
> > 
> > 那荧的mod有着落了？我都等了好久了
> 
> 要是权重不出错，昨天应该就出了。

要保留的部分还需要修改权重吗

**Comment by abyss1103** [comment]
> > > > > 没有模型用估计也用甘雨的。 等我弄一下新神子你看看行里就不行了。
> > > > 
> > > > 
> > > > buffer就是Github里面的那个如果不是可以讲一下吗，我小白想试试看吗
> > > 
> > > 
> > > SilentNightSound大佬实现了脚本，让我们快捷的实现导出功能，也替我们导出了事务模型 [。](https://github.com/SilentNightSound)
> > 
> > 
> > 那荧的mod有着落了？我都等了好久了
> 
> 要是权重不出错，昨天应该就出了。

原角色要保留的部分还要在甘雨对应部分修改权重吗

**Comment by hxhxzd** [comment]
> > > 看不见，添加照片的时候。等他加载完再上传。 没加载完会有uploading字样。 另外，反虚化软件有嘛？
> > 
> > 
> > 或者说能详细说说您的制作过程吗
> 
> 我的参照的教程、模型和贴图都来自[GI-Model-Importer](https://github.com/SilentNightSound/GI-Model-Importer)这个项目。 里面有大佬写的中文教程。推荐观看。
> 
> 模型修改，再导入挺简单的。
> 
> 这几天换模型参照的[Genshin Impact model Importing with 3dmigoto - Tutorial](https://www.youtube.com/watch?v=7ijMOjhEvBw&t=1519s)这个视频的流程。

我观看了你分享的视频，我现在有一些问题。
如果我将一个角色模型和一个R18模型导入Blender后，就是可以从演示视频的双开绘制权重开始吗？权重修改后相当于被修改部分凸显出来吗？视频中的修改贴图部分，可以分别将两个模型的贴图的贴图导入吗？
我最近才刚接触这一类软件（模型），如果您能够回答我的问题，那么将会给我很大的帮助！

**Comment by abyss1103** [comment]
uv图明明对上了但模型上却啥都没对上，你神里的Blender为什么没用uv图

**Comment by abyss1103** [comment]
> 而且我也不太会从buffer里找模型。 没有模型用估计也只有用甘雨的。 等我弄一下新神子你看看行不行。
![屏幕截图 2022-07-27 230545](https://user-images.githubusercontent.com/107688386/181282220-c58cd3b8-e28f-44fb-a5f4-5e3ff2babc1e.png)
这是什么问题

**Comment by zeroruka** [comment]
https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/Troubleshooting.md

**Comment by fengyan11** [comment]
zerouka发刻晴blend文件了，有大佬做mod吗？求一个心海的或者再做一个旅行者的，不会缝合

**Comment by luoluojialuo** [comment]
> https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/Troubleshooting.md

您的刻晴模型是根据什么模型改出来的？太厉害了

**Comment by fengyan11** [comment]
> > > 看不见，添加照片的时候。等他加载完再上传。 没加载完会有uploading字样。 另外，反虚化软件有嘛？
> > 
> > 
> > 或者说能详细说说您的制作过程吗
> 
> 我的参照的教程、模型和贴图都来自[GI-Model-Importer](https://github.com/SilentNightSound/GI-Model-Importer)这个项目。 里面有大佬写的中文教程。推荐观看。
> 
> 模型修改，再导入挺简单的。
> 
> 这几天换模型参照的[Genshin Impact model Importing with 3dmigoto - Tutorial](https://www.youtube.com/watch?v=7ijMOjhEvBw&t=1519s)这个视频的流程。

那英文教程看得我脑壳疼，一个字都不认识(=_=)

**Comment by luoluojialuo** [comment]
> > > 看不见，添加照片的时候。等他加载完再上传。 没加载完会有uploading字样。 另外，反虚化软件有嘛？
> > 
> > 
> > 或者说能详细说说您的制作过程吗
> 
> 我的参照的教程、模型和贴图都来自[GI-Model-Importer](https://github.com/SilentNightSound/GI-Model-Importer)这个项目。 里面有大佬写的中文教程。推荐观看。
> 
> 模型修改，再导入挺简单的。
> 
> 这几天换模型参照的[Genshin Impact model Importing with 3dmigoto - Tutorial](https://www.youtube.com/watch?v=7ijMOjhEvBw&t=1519s)这个视频的流程。

我用大家分享的blend去拼接后做出来的模型形体与运动上都没有问题，但是被拼接的部分在游戏里会有较粗的棕色轮廓，这个要怎么消除？比如芭芭拉的blend，直接导出是没有问题的，但是在我这倒过一手后，属于芭芭拉blend中的那部分模型就有勾边轮廓。这个是教程里提到的outline嘛？另外 教程联动的blender插件库中 去除outline的插件怎么使用？还请指教

**Comment by zeroruka** [comment]
> 我用大家分享的blend去拼接后做出来的模型形体与运动上都没有问题，但是被拼接的部分在游戏里会有较粗的棕色轮廓，这个要怎么消除？比如芭芭拉的blend，直接导出是没有问题的，但是在我这倒过一手后，属于芭芭拉blend中的那部分模型就有勾边轮廓。这个是教程里提到的outline嘛？另外 教程联动的blender插件库中 去除outline的插件怎么使用？还请指教

https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/Troubleshooting.md#thick-or-abnormal-color-outlines
![image](https://user-images.githubusercontent.com/89210318/182401078-c2cb96c7-6435-472a-b77b-733124ead241.png)

**Comment by zeroruka** [comment]
> 您的刻晴模型是根据什么模型改出来的？太厉害了

用的是[Shirakami](https://www.patreon.com/shirakami)的模型，我自己又基于他的模型做了一些改动。

**Comment by CappuCoco** [comment]
> > 看不见，添加照片的时候。等他加载完再上传。没加载完会有上传字样。 另外，反虚化软件有嘛？
> 
> 链接:[https://pan.baidu.com/s/1UYBQFEC39ciRdcPWOYs3JQ 提取码:wtjk hi，这是我用百度网盘分享的内容~复制这段内容打开「百度网盘」APP即可获取](https://pan.baidu.com/s/1UYBQFEC39ciRdcPWOYs3JQ%C2%A0%E6%8F%90%E5%8F%96%E7%A0%81:wtjk%C2%A0hi%EF%BC%8C%E8%BF%99%E6%98%AF%E6%88%91%E7%94%A8%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E5%88%86%E4%BA%AB%E7%9A%84%E5%86%85%E5%AE%B9~%E5%A4%8D%E5%88%B6%E8%BF%99%E6%AE%B5%E5%86%85%E5%AE%B9%E6%89%93%E5%BC%80%E3%80%8C%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E3%80%8DAPP%E5%8D%B3%E5%8F%AF%E8%8E%B7%E5%8F%96) 解压随便放进一个文件夹，打开第一次让他获取原神的位置，第二次打开让他直接进去原神就好了 官服也可以用，部分私服改了补丁用不了目前只支持2.8版本 以下是效果 ![Uploading
> 
> > #@20220725221716.png…](
> > ![IMG_20220725_220639](https://user-images.githubusercontent.com/109934183/180905130-046cda68-1b63-45ef-a577-e95fe0058603.jpg)
> > )
> > ![IMG_20220723_221848](https://user-images.githubusercontent.com/109934183/180905208-2b73543b-9d14-4eda-a9d7-72501954d3a3.jpg)
> > 我只能看到图片的代码，不清楚有没有加载完

大佬链接失效了，求补

**Comment by djjsns** [comment]
> > > 看不见，添加照片的时候。等他加载完再上传。没加载完会有上传字样。 另外，反虚化软件有嘛？
> > 
> > 
> > 链接:[https://pan.baidu.com/s/1UYBQFEC39ciRdcPWOYs3JQ提取码:wtjk嗨，这是我用百度网盘分享的内容~复制这段内容打开「百度网盘」APP即可获取](https://pan.baidu.com/s/1UYBQFEC39ciRdcPWOYs3JQ%C2%A0%E6%8F%90%E5%8F%96%E7%A0%81:wtjk%C2%A0hi%EF%BC%8C%E8%BF%99%E6%98%AF%E6%88%91%E7%94%A8%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E5%88%86%E4%BA%AB%E7%9A%84%E5%86%85%E5%AE%B9~%E5%A4%8D%E5%88%B6%E8%BF%99%E6%AE%B5%E5%86%85%E5%AE%B9%E6%89%93%E5%BC%80%E3%80%8C%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E3%80%8DAPP%E5%8D%B3%E5%8F%AF%E8%8E%B7%E5%8F%96)解压随便放进一个文件夹,打开第一次让他获取原神的位置,第二次打开让他直接进去原神就好了 官服也可以用,部分私服改了补丁用不了目前只支持2.8版本 以下是效果！[上传
> > > #@20220725221716.png…](
> > > ![IMG_20220725_220639](https://user-images.githubusercontent.com/109934183/180905130-046cda68-1b63-45ef-a577-e95fe0058603.jpg)
> > > )
> > > ![IMG_20220723_221848](https://user-images.githubusercontent.com/109934183/180905208-2b73543b-9d14-4eda-a9d7-72501954d3a3.jpg)
> > > 我只能看到图片的代码，不清楚有没有加载完
> 
> 大佬链接失效了，求补

https://sspace.lanzouv.com/iGxfN08aj1va
密码:1m7u
https://sspace.lanzouv.com/i3unh08aj1ih
密码:i4s0

**Comment by CappuCoco** [comment]
> > > > 看不见，添加照片的时候。等他加载完再上传。没加载完会有上传字样。 另外，反虚化软件有嘛？
> > > 
> > > 
> > > 链接:[https://pan.baidu.com/s/1UYBQFEC39ciRdcPWOYs3JQ提取码:wtjk嗨，这是我用百度网盘分享的内容~复制这段内容打开「百度网盘」APP即可获取](https://pan.baidu.com/s/1UYBQFEC39ciRdcPWOYs3JQ%C2%A0%E6%8F%90%E5%8F%96%E7%A0%81:wtjk%C2%A0hi%EF%BC%8C%E8%BF%99%E6%98%AF%E6%88%91%E7%94%A8%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E5%88%86%E4%BA%AB%E7%9A%84%E5%86%85%E5%AE%B9~%E5%A4%8D%E5%88%B6%E8%BF%99%E6%AE%B5%E5%86%85%E5%AE%B9%E6%89%93%E5%BC%80%E3%80%8C%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E3%80%8DAPP%E5%8D%B3%E5%8F%AF%E8%8E%B7%E5%8F%96)解压随便放进一个文件夹,打开第一次让他获取原神的位置,第二次打开让他直接进去原神就好了 官服也可以用,部分私服改了补丁用不了目前只支持2.8版本 以下是效果！[上传
> > > > #@20220725221716.png…](
> > > > ![IMG_20220725_220639](https://user-images.githubusercontent.com/109934183/180905130-046cda68-1b63-45ef-a577-e95fe0058603.jpg)
> > > > )
> > > > ![IMG_20220723_221848](https://user-images.githubusercontent.com/109934183/180905208-2b73543b-9d14-4eda-a9d7-72501954d3a3.jpg)
> > > > 我只能看到图片的代码，不清楚有没有加载完
> > 
> > 
> > 大佬链接失效了，求补
> 
> https://sspace.lanzouv.com/iGxfN08aj1va 密码:1m7u https://sspace.lanzouv.com/i3unh08aj1ih 密码:i4s0

感谢
